AutoTestPlatform/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'atp/',include("main_platform.urls",namespace= "main_platform")),
    url(r'sea/',include("selenium_apps.urls",namespace= "selenium_apps")),
    url(r"sendmail/",include("send_mails.urls")),
]

SendMail/urls.py
from django.conf.urls import url
from SendMail import views



# app_name= "[UserAuthAndPermission]"
urlpatterns= [
    url(r'^email/', views.email),
    url(r'^get_result/', views.get_result),
]

main_platform/urls.py
from django.urls import re_path,path
from main_platform import views


app_name= "[main_platform]"
urlpatterns= [
    path(r'get_test/', views.get_test,name= "get_test"),
    path(r'post_test/', views.post_test,name= "post_test"),
    path(r'put_test/', views.put_test,name= "put_test"),
    # 本机测试使用

    path(r'index/', views.index,name= "index"),
    path(r'login/', views.login,name= "login"),
    path(r'get_code/', views.get_code,name= "get_code"),
    path(r'logout/', views.logout,name= "logout"),
    # 登录相关

    path(r'project/', views.project,name= "project"),
    path(r'module/', views.module,name= "module"),
    path(r'test_case/', views.test_case,name= "test_case"),
    re_path(r'^test_case_detail/(?P<caseid>\d+)/', views.test_case_detail,name= "test_case_detail"),
    # 模块相关

    path(r'down_test_template/', views.down_test_template,name= "down_test_template"),
    path(r'up_test_template/', views.up_test_template,name= "up_test_template"),
    path(r'add_test_case/', views.add_test_case,name= "add_test_case"),
    re_path(r'^update_test_case/(?P<caseid>\d+)/', views.update_test_case,name= "update_test_case"),
    re_path(r'^delete_test_case/(?P<caseid>\d+)/', views.delete_test_case,name= "delete_test_case"),
    path(r'check_module_belong_project/',
        views.check_module_belong_project,name= "check_module_belong_project"),
    path(r'down_test_template/', views.down_test_template,name= "down_test_template"),
    re_path(r'^module_test_case/(?P<moduleid>\d+)/', views.module_test_case, name="module_test_case"),
    # 新增用例相关

    path(r'test_suite/', views.test_suite,name= "test_suite"),
    re_path(r'^add_case_into_suite/(?P<suiteid>\d+)/', views.add_case_into_suite,name= "add_case_into_suite"),
    re_path(r'^view_or_delete_cases_in_suite/(?P<suiteid>\d+)/', views.view_or_delete_cases_in_suite,
        name= "view_or_delete_cases_in_suite"),
    # 用例集相关

    re_path(r'test_execute/(?P<jobid>[\s\S]*)/', views.test_execute, name= "test_execute"),
    re_path(r'^down_test_execute_template/(?P<id>\d+)/',
        views.down_test_execute_template, name= "down_test_execute_template"),
    re_path(r'^test_case_execute_record/(?P<id>\d+)/',
        views.test_case_execute_record, name= "test_case_execute_record"),
    re_path('test_execute_show_exception/(?P<execute_id>[0-9]+)$',
            views.test_execute_show_exception, name= "test_execute_show_exception"),
    re_path('testsuite_execute_show_exception/(?P<execute_id>[0-9]+)$',
            views.testsuite_execute_show_exception, name="testsuite_execute_show_exception"),
    re_path(r'^test_suite_execute_record/(?P<id>\d+)/(?P<statistics>\d+)/',
        views.test_suite_execute_record, name= "test_suite_execute_record"),
    # 执行记录相关

    re_path(r'^test_suite_statistics/(?P<suite_id>\d+)/',
            views.test_suite_statistics, name="test_suite_statistics"),
    re_path(r'^test_suite_tc_execute_record/(?P<id>\d+)/',
            views.test_suite_test_case_execute_record,
            name="test_suite_tc_execute_record"),  # 地址路径不能过长，导致读取不出id
    re_path(r'^module_test_case_statistics/(?P<module_id>\d+)/',
            views.module_test_case_statistics, name="module_test_case_statistics"),
    re_path(r'^project_test_case_statistics/(?P<project_id>\d+)/',
            views.project_test_case_statistics, name="project_test_case_statistics"),
    # 统计结果相关

    path(r'job_execute/', views.job_execute, name= "job_execute"),
    re_path(r'^change_job_status/(?P<id>([\s\S]*))/(?P<status>\d+)/',
            views.change_job_status, name= "change_job_status"),
    path(r'test_case/atp/get_job_name/',views.get_job_name, name= "get_job_name"),
    path(r'test_suite/atp/get_job_name/',views.get_job_name, name= "get_job_name"),
    # 任务相关
]

templates/add_test_case.html
{% extends 'base.html' %}
{% load static %}
{% block title %}添加用例{% endblock %}

{% block content %}
    <div class="container">
        <form method="post" action="{% url 'main_platform:add_test_case' %}" onsubmit="return check()">
            {% csrf_token %}

            <div class="form-group">
                <label for="case_name_input" class="col-sm-2 control-label" style="font-size: 15px">用例名称:</label>
                <input type="text" class="col-sm-7 input-group" placeholder="请输入用例名称"
                       name="case_name" maxlength="25" id="case_name_input"
                       style="width: 665px;height: 26px;border: 1px solid black;font-size: 14px;">
                <span id="case_name_info"></span> 
            </div>
            <br>

            <div class="form-group">
                <label for="belong_project_input" class="col-sm-2 control-label" style="font-size: 15px">所属项目:</label>
                <input type="text" list="projects" placeholder="请选择所属项目" id="belong_project_input"
                       class="col-sm-7 input-group" name="belong_project">
                <datalist id="projects">
                    {% for bp in belong_project %}
                        <option>{{ bp.name }}</option>
                    {% endfor %}
                </datalist>
                <span id="belong_project_info"></span> 
            </div>
            <br>

            <div class="form-group">
                <label for="belong_module_input" class="col-sm-2 control-label" style="font-size: 15px">所属模块:</label>
                <input type="text" list="modules" placeholder="请选择所属模块" id="belong_module_input"
                       class="col-sm-7 input-group" name="belong_module">
                <datalist id="modules">
                    {% for bm in belong_module %}
                        <option>{{ bm.name }}</option>
                    {% endfor %}
                </datalist>
                <span id="belong_module_info"></span>
            </div>
            <br>

            <div class="form-group">
                <label for="request_data_input" class="col-sm-2 control-label" style="font-size: 15px">请求数据:</label>
                <input type="text" class="col-sm-7 input-group" placeholder="请输入请求数据"
                       name="request_data" maxlength="256" id="request_data_input"
                       style="width: 665px;height: 26px;border: 1px solid black;font-size: 14px;">
                <span id="request_data_info"></span> 
            </div>
            <br>

            <div class="form-group">
                <label for="uri_input" class="col-sm-2 control-label" style="font-size: 15px">接口地址:</label>
                <input type="text" class="col-sm-7 input-group" placeholder="请输入接口地址"
                       name="uri" maxlength="128" id="uri_input"
                       style="width: 665px;height: 26px;border: 1px solid black;font-size: 14px;">
                <span id="uri_info"></span> 
            </div>
            <br>

            <div class="form-group">
                <label for="assert_key_input" class="col-sm-2 control-label" style="font-size: 15px">断言内容:</label>
                <input type="text" class="col-sm-7 input-group" placeholder="请输入断言内容"
                       name="assert_key" maxlength="128" id="assert_key_input"
                       style="width: 665px;height: 26px;border: 1px solid black;font-size: 14px;">
                <span id="assert_key_info"></span> 
            </div>
            <br>

            <div class="form-group">
                <label for="maintainer_input" class="col-sm-2 control-label" style="font-size: 15px">编写人员:</label>
                <input type="text" class="col-sm-7 input-group" value="{{ maintainer }}"
                       name="maintainer" disabled="disabled" id="maintainer_input"
                       style="width: 665px;height: 26px;border: 1px solid black;font-size: 14px;">
                <span id="maintainer_info"></span> 
            </div>
            <br>

            <div class="form-group">
                <label for="extract_var_input" class="col-sm-2 control-label" style="font-size: 15px">提取变量表达式:</label>
                <input type="text" class="col-sm-7 input-group" placeholder="请输入提取变量表达式"
                       name="extract_var" maxlength="256" id="extract_var_input"
                       style="width: 665px;height: 26px;border: 1px solid black;font-size: 14px;">
                <span id="extract_var_info"></span> 
            </div>
            <br>

            <div class="form-group">
                <label for="request_method_input" class="col-sm-2 control-label" style="font-size: 15px">请求方式:</label>
                <input type="text" list="methods" placeholder="请选择请求方式" name="request_method"
                id="request_method_input">
                <datalist id="methods">
                    {% for rm in request_method %}
                        <option>{{ rm }}</option>
                    {% endfor %}
                </datalist>
                <br>
                <span id="request_method_info"></span> 
            </div>
            <br>

            <div class="form-group">
                <label for="status_input" class="col-sm-2 control-label" style="font-size: 15px">用例状态:</label>
                <input type="text" class="col-sm-7 input-group" value="0"
                       name="status" disabled="disabled" id="status_input"
                       style="width: 665px;height: 26px;border: 1px solid black;font-size: 14px;">
                <span id="status_info"></span> 
            </div>
            <br>

            <div class="form-group">
                <label for="related_case_id_input" class="col-sm-2 control-label" style="font-size: 15px">关联用例id:</label>
                <input type="number" class="col-sm-7 input-group" placeholder="请输入关联用例id"
                       name="related_case_id" min="1" max="9999" id="related_case_id_input"
                       style="width: 665px;height: 26px;border: 1px solid black;font-size: 14px;">
                <span id="related_case_id_info"></span>
            </div>
            <br>

            <div class="form-group">
                <label for="user_input" class="col-sm-2 control-label" style="font-size: 15px">责任人:</label>
                <input type="text" list="users" placeholder="请选择责任人"
                       class="col-sm-7 input-group" name="user" id="user_input">
                <datalist id="users">
                    {% for u in user %}
                        <option>{{ u.username }}</option>
                    {% endfor %}
                </datalist>
                <span id="user_info"></span>
            </div>
            <br>

            <button type="submit" class="btn btn-success btn-block"
                    style="width: 250px;height: 45px;display:block;margin:0 auto">提交</button>
        </form>
    </div>
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/add_test_case.js' %}"></script>
{% endblock %}

templates/base.html
<html lang="zh-CN">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}base{% endblock %}</title>

    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    {% block css %}
    {% endblock %}
</head>


<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav"
                    aria-expanded="false">
                <span class="sr-only">切换导航条</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" style="color: #2aabd2" href="{% url 'main_platform:index' %}">自动化测试平台</a>
        </div>

        <div class="collapse navbar-collapse" id="my-nav">
            <ul class="nav navbar-nav navbar-left">
                <li class="active"><a href="{% url 'main_platform:project' %}">测试项目</a></li>
                <li class="active"><a href="{% url 'main_platform:module' %}">测试模块</a></li>
                <li class="active"><a href="{% url 'main_platform:test_case' %}">测试用例</a></li>
                <li class="active"><a href="{% url 'main_platform:test_suite' %}">用例集合</a></li>
                <li class="active"><a href="{% url 'main_platform:test_execute' 'None' %}">执行结果</a></li>
                <li class="active"><a href="{% url 'main_platform:job_execute' %}">定时任务</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="#">当前在线：{{ user.username }}</a></li>
                    <li><a href="{% url 'main_platform:logout' %}">登出</a></li>
                {% else %}
                    <li><a href="{% url 'main_platform:login' %}">登录</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}
</body>


{% block ext_js %}
    <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock %}


</html>

templates/job_execute.html
{% extends 'base.html' %}
{% load static %}
{% block title %}定时任务{% endblock %}

{% block content %}
    <form action="{% url 'main_platform:job_execute' %}" method="POST">
        {% csrf_token %}
        <input style="margin-left: 5px;" type="text" name="job_name" value="{{ job_name }}" placeholder="输入任务名称">
        <input type="submit" value="搜索">
    </form>

    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th width="10%">id</th>
                <th width="25%">任务名称</th>
                <th width="25%">执行时间</th>
                <th width="10%">任务提交人</th>
                <th width="15%">操作</th>
            </tr>
            </thead>
            <tbody>

            {% for job in pages %}
                <tr>
                    <td>{{ job.id }}</td>
                    <td>{{ job.job_id }}</td>
                    <td>{{ job.run_time|date:"Y-n-d H:i" }}</td>
                    <td>{{ job.user }}</td>
                    <td>
                        {% ifequal job.status 1 %}
                            <a href="{% url 'main_platform:test_execute' job.job_id %}" target="_blank">
                                <button class="btn-success">查看结果</button>
                            </a>
                        {% endifequal %}
                        <a href="{% url 'main_platform:change_job_status' job.job_id 2 %}">
                            <button class="btn-danger">删除任务</button>
                        </a>
                        {% ifequal job.status 3 %}
                            <a href="{% url 'main_platform:change_job_status' job.job_id 0 %}">
                                <button class="btn-warning">启动任务</button>
                            </a>
                        {% endifequal %}
                        {% ifequal job.status 0 %}
                            <a href="{% url 'main_platform:change_job_status' job.job_id 3 %}">
                                <button class="btn-warning">暂停任务</button>
                            </a>
                        {% endifequal %}

                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div id="pages" class="text-center">
        <nav>
            <ul class="pagination">
                <li class="step-links">
                    {% if pages.has_previous %}
                        <a class='active' href="?page={{ pages.previous_page_number }}">上一页</a>
                    {% endif %}

                    <span class="current">
                        第 {{ pages.number }} 页 / 共 {{ pages.paginator.num_pages }} 页</span>

                    {% if pages.has_next %}
                        <a class='active' href="?page={{ pages.next_page_number }}">下一页</a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}登录{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="col-md-4 col-md-offset-4">
        <form class='form-login' action="{% url 'main_platform:login' %}" method="post">
            {% csrf_token %}
            <h2 class="text-center">欢迎登录</h2>

            <div class="form-group">
                {{ login_form.username.label_tag }}
                {{ login_form.username}}
            </div>
            <div class="form-group">
                {{ login_form.password.label_tag }}
                {{ login_form.password }}
            </div>

            <div class="form-group">
                <label for="verifypassword_input">验证码</label>
                <input type="password" class="form-control"
                       id="verifypassword_input" placeholder="请输入验证码，区分大小写"
                       name="verify_code">
                <img src="{% url '[main_platform]:get_code' %}" alt="未获取到验证码" style="margin: 0.2rem 0">
            </div>

            {% if request.session.message %}
                <div class="alert alert-warning">{{ request.session.message }}</div>
            {% endif %}

            <button type="submit" class="btn btn-primary btn-block" >登录系统</button>
        </form>
    </div>
</div>
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/login.js' %}"></script>
{% endblock %}

templates/project.html
{% extends 'base.html' %}
{% load static %}
{% block title %}测试项目{% endblock %}

{% block content %}
<form action="{% url 'main_platform:project'%}" method="POST">
    {% csrf_token %}
    <input style="margin-left: 5px;" type="text" name="proj_name" value="{{ proj_name }}" placeholder="输入项目名称">
    <input type="submit" value="搜索">
</form>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
{#            <th>id</th>#}
            <th>项目名称</th>
            <th>项目负责人</th>
            <th>测试负责人</th>
            <th>开发负责人</th>
            <th>简要描述</th>
            <th>创建时间</th>
            <th>更新时间</th>
            <th>测试结果统计</th>
        </tr>
        </thead>
        <tbody>

        {% for project in pages %}
        <tr>
{#            <td>{{ project.id }}</td>#}
            <td>{{ project.name }}</td>
            <td>{{ project.proj_owner }}</td>
            <td>{{ project.test_owner }}</td>
            <td>{{ project.dev_owner }}</td>
            <td>{{ project.desc }}</td>
            <td>{{ project.create_time|date:"Y-n-d H:i:s" }}</td>
            <td>{{ project.update_time|date:"Y-n-d H:i:s" }}</td>
            <td><a href="{% url 'main_platform:project_test_case_statistics' project.id %}"> 查看</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<div id="pages" class="text-center">
    <nav>
        <ul class="pagination">
            <li class="step-links">
                {% if pages.has_previous %}
                <a class='active' href="?page={{ pages.previous_page_number }}">上一页</a>
                {% endif %}

                <span class="current">
                        第 {{ pages.number }} 页 / 共 {{ pages.paginator.num_pages }} 页</span>

                {% if pages.has_next %}
                <a class='active' href="?page={{ pages.next_page_number }}">下一页</a>
                {% endif %}
            </li>
        </ul>
    </nav>
</div>
{% endblock %}

templates/test_case.html
{% extends 'base.html' %}
{% load static %}
{% block title %}测试用例{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/test_case.css' %}">
{% endblock %}

{% block content %}
    <div id="group">
        <div id="search">
            <form action="{% url 'main_platform:test_case' %}" method="POST">
                {% csrf_token %}
                <input style="margin-left: 5px;" type="text" name="case_name" value="{{ case_name }}"
                       placeholder="输入用例名称">
                <input type="submit" value="搜索">
            </form>
        </div>

        <div id="load">
            <div id="addcase">
                <a href="{% url 'main_platform:add_test_case' %}">添加测试用例</a>
            </div>

            <div id="downloads">
                <form action="">
                    <a type="button" href="{% url 'main_platform:down_test_template' %}">下载模板文件</a>
                </form>
            </div>

            <div id="uploads">
                <form action="{% url 'main_platform:up_test_template' %}" method="post" enctype="multipart/form-data">
                    <div class="upload-btn-wrapper">
                        {% csrf_token %}
                        <button class="btn">选择模板文件</button>
                        <input type="file" name="file_name" accept="application/vnd.ms-excel">
                        {#只接受xls文件#}
                    </div>
                    <button id='upload-xls' class="btn" type="submit">上传模板文件</button>
                </form>
            </div>
        </div>

    </div>

    <form action="" method="POST">
        {% csrf_token %}
        <span style="margin-left: 5px;font-size: 15px">运行环境：</span>
        <select name="env">
            <option selected value="dev" style="font-size: 15px">dev</option>
            <option value="test" style="font-size: 15px">test</option>
            <option value="https" style="font-size: 15px">https</option>
        </select>
        <input type="datetime-local" style="font-size: 10px" name="ex_time">
        <input style="margin-left: 5px;font-size: 10px" type="submit" value='执行测试用例' name="ex_case" onclick="return ischecked()"/>
        <p class="glyphicon glyphicon-info-sign" title="设置执行时间，默认下一分钟后执行"></p>

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th width="5%"><input type="checkbox" id="all_select" onclick="selectOrCancelAll();"/>全选</th>
                    <th width="8.75%">用例名称</th>
                    <th width="8.75%">所属项目</th>
                    <th width="8.75%">所属模块</th>
                    <th width="8.75%">接口地址</th>
                    <th width="5%">请求方式</th>
                    <th width="12.5%">请求数据</th>
                    <th width="8.75%">断言key</th>
                    <th width="8.75%">关联用例ID</th>
                    <th width="20%">提取变量表达式</th>
                    <th width="5%">操作</th>
                </tr>
                </thead>
                <tbody>

                {% for test_case in pages %}
                    <tr>
                        <td><input type="checkbox" value="{{ test_case.id }}" name="testcases_list"> {{ test_case.id }}
                        </td>
                        <td>
                            <a href="{% url 'main_platform:test_case_detail' test_case.id %}" target="_blank">{{ test_case.case_name }}</a>
                        </td>
                        <td>{{ test_case.belong_project.name }}</td>
                        <td>{{ test_case.belong_module.name }}</td>
                        <td>{{ test_case.uri }}</td>
                        <td>{{ test_case.request_method }}</td>
                        <td>{{ test_case.request_data }}</td>
                        <td>{{ test_case.assert_key }}</td>
                        <td>{{ test_case.related_case_id }}</td>
                        <td>{{ test_case.extract_var }}</td>
                        <td>
                            <a href="{% url 'main_platform:update_test_case' test_case.id %}">修改</a>
                            <a href="{% url 'main_platform:delete_test_case' test_case.id %}">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </form>

    <div id="pages" class="text-center">
        <nav>
            <ul class="pagination">
                <li class="step-links">
                    {% if pages.has_previous %}
                        <a class='active' href="?page={{ pages.previous_page_number }}">上一页</a>
                    {% endif %}

                    <span class="current">
                        第 {{ pages.number }} 页 / 共 {{ pages.paginator.num_pages }} 页</span>

                    {% if pages.has_next %}
                        <a class='active' href="?page={{ pages.next_page_number }}">下一页</a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>

{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/test_case.js' %}"></script>
{% endblock %}

templates/test_suite.html
{% extends 'base.html' %}
{% load static %}
{% block title %}用例集合{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/test_suite.css' %}">
{% endblock %}

{% block content %}
    <div id="group">
        <div id="search">
            <form action="{% url 'main_platform:test_suite' %}" method="POST">
                {% csrf_token %}
                <input style="margin-left: 5px;" type="text" name="suite_name" value="{{ suite_name }}"
                       placeholder="输入集合名称">
                <input type="submit" value="搜索">
            </form>
        </div>
    </div>

    <form action="" method="POST">
        {% csrf_token %}
        <span style="margin-left: 5px;">运行环境：</span>
        <select name="env">
            <option selected value="dev">dev</option>
            <option value="test">test</option>
            <option value="https">https</option>
        </select>
        <input type="datetime-local" style="font-size: 10px" name="ex_time">
        <input style="margin-left: 5px;font-size: 10px" type="submit" value='执行测试集合' name="ex_suite" onclick="return ischecked()"/>
        <p class="glyphicon glyphicon-info-sign" title="设置执行时间，默认下一分钟后执行"></p>


        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><input type="checkbox" id="all_select" onclick="selectOrCancelAll();"/>全选</th>
                    <th>id</th>
                    <th>测试集合名称</th>
                    <th>创建者</th>
                    <th>创建时间</th>
                    <th>查看/删除测试用例</th>
                    <th>添加测试用例</th>
                    <th>用例集合执行结果</th>
                </tr>
                </thead>
                <tbody>

                {% for case_suite in pages %}
                    <tr>
                        <td><input type="checkbox" value="{{ case_suite.id }}" name="testsuite_list"></td>
                        <td>{{ case_suite.id }}</td>
                        <td>{{ case_suite.suite_desc }}</td>
                        <td>{{ case_suite.creator }}</td>
                        <td>{{ case_suite.create_time|date:"Y-n-d H:i:s" }}</td>
                        <td>
                            <a href="{% url 'main_platform:view_or_delete_cases_in_suite' case_suite.id %}">查看/删除测试用例</a>
                        </td>
                        <td><a href="{% url 'main_platform:add_case_into_suite' case_suite.id %}">添加测试用例</a></td>
                        <td><a href="{% url '[main_platform]:test_suite_statistics' case_suite.id %}">查看用例集合执行结果</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </form>

    <div id="pages" class="text-center">
        <nav>
            <ul class="pagination">
                <li class="step-links">
                    {% if pages.has_previous %}
                        <a class='active' href="?page={{ pages.previous_page_number }}">上一页</a>
                    {% endif %}

                    <span class="current">
                        第 {{ pages.number }} 页 / 共 {{ pages.paginator.num_pages }} 页</span>

                    {% if pages.has_next %}
                        <a class='active' href="?page={{ pages.next_page_number }}">下一页</a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/test_suite.js' %}"></script>
{% endblock %}

templates/test_suite_execute_records.html
{% extends 'base.html' %}
{% load static %}
{% block title %}集合执行记录{% endblock %}

{% block content %}

    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>id</th>
                <th>集合名称</th>
                <th>执行状态</th>
                <th>集合结果</th>
                <th>用例结果</th>
                <th>创建者</th>
                <th>创建时间</th>
            </tr>
            </thead>
            <tbody>

            {% for test_suite_execute_record in pages %}
                <tr>
                    <td>{{ test_suite_execute_record.id }}</td>
                    <td>{{ test_suite_execute_record.test_suite.suite_desc }}</td>
                    {% ifequal test_suite_execute_record.status 1 %}
                        <td>执行完毕</td>
                    {% else %}
                        <td>待执行</td>
                    {% endifequal %}

                    {% ifequal test_suite_execute_record.test_result '成功' %}
                        <td style="color: green">{{ test_suite_execute_record.test_result }}</td>
                    {% else %}
                        <td style="color: red">{{ test_suite_execute_record.test_result }}</td>
                    {% endifequal %}
                    <td><a href="{% url 'main_platform:test_suite_tc_execute_record' test_suite_execute_record.id %}">
                        用例执行结果</a></td>
                    <td>{{ test_suite_execute_record.creator }}</td>
                    <td>{{ test_suite_execute_record.create_time|date:"Y-n-d H:i" }}</td>
                </tr>
            {% endfor %}


            </tbody>
        </table>
    </div>

    <div id="pages" class="text-center">
        <nav>
            <ul class="pagination">
                <li class="step-links">
                    {% if pages.has_previous %}
                        <a class='active' href="?page={{ pages.previous_page_number }}">上一页</a>
                    {% endif %}

                    <span class="current">
                        第 {{ pages.number }} 页 / 共 {{ pages.paginator.num_pages }} 页</span>

                    {% if pages.has_next %}
                        <a class='active' href="?page={{ pages.next_page_number }}">下一页</a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>
    </div>
{% endblock %}