AutoTestPlatform/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'atp/',include("main_platform.urls",namespace= "main_platform")),
    url(r'sea/',include("selenium_apps.urls",namespace= "selenium_apps")),
    url(r"sendmail/",include("send_mails.urls")),
]

SendMail/urls.py
from django.conf.urls import url
from SendMail import views



# app_name= "[UserAuthAndPermission]"
urlpatterns= [
    url(r'^email/', views.email),
    url(r'^get_result/', views.get_result),
]

main_platform/urls.py
from django.urls import re_path,path
from main_platform import views


app_name= "[main_platform]"
urlpatterns= [
    path(r'get_test/', views.get_test,name= "get_test"),
    path(r'post_test/', views.post_test,name= "post_test"),
    path(r'put_test/', views.put_test,name= "put_test"),
    # 本机测试使用

    path(r'index/', views.index,name= "index"),
    path(r'login/', views.login,name= "login"),
    path(r'get_code/', views.get_code,name= "get_code"),
    path(r'logout/', views.logout,name= "logout"),
    # 登录相关

    path(r'project/', views.project,name= "project"),
    path(r'module/', views.module,name= "module"),
    path(r'test_case/', views.test_case,name= "test_case"),
    re_path(r'^test_case_detail/(?P<caseid>\d+)/', views.test_case_detail,name= "test_case_detail"),
    # 模块相关

    path(r'down_test_template/', views.down_test_template,name= "down_test_template"),
    path(r'up_test_template/', views.up_test_template,name= "up_test_template"),
    path(r'add_test_case/', views.add_test_case,name= "add_test_case"),
    re_path(r'^update_test_case/(?P<caseid>\d+)/', views.update_test_case,name= "update_test_case"),
    re_path(r'^delete_test_case/(?P<caseid>\d+)/', views.delete_test_case,name= "delete_test_case"),
    path(r'check_module_belong_project/',
        views.check_module_belong_project,name= "check_module_belong_project"),
    path(r'down_test_template/', views.down_test_template,name= "down_test_template"),
    re_path(r'^module_test_case/(?P<moduleid>\d+)/', views.module_test_case, name="module_test_case"),
    # 新增用例相关

    path(r'test_suite/', views.test_suite,name= "test_suite"),
    re_path(r'^add_case_into_suite/(?P<suiteid>\d+)/', views.add_case_into_suite,name= "add_case_into_suite"),
    re_path(r'^view_or_delete_cases_in_suite/(?P<suiteid>\d+)/', views.view_or_delete_cases_in_suite,
        name= "view_or_delete_cases_in_suite"),
    # 用例集相关

    re_path(r'test_execute/(?P<jobid>[\s\S]*)/', views.test_execute, name= "test_execute"),
    re_path(r'^down_test_execute_template/(?P<id>\d+)/',
        views.down_test_execute_template, name= "down_test_execute_template"),
    re_path(r'^test_case_execute_record/(?P<id>\d+)/',
        views.test_case_execute_record, name= "test_case_execute_record"),
    re_path('test_execute_show_exception/(?P<execute_id>[0-9]+)$',
            views.test_execute_show_exception, name= "test_execute_show_exception"),
    re_path('testsuite_execute_show_exception/(?P<execute_id>[0-9]+)$',
            views.testsuite_execute_show_exception, name="testsuite_execute_show_exception"),
    re_path(r'^test_suite_execute_record/(?P<id>\d+)/(?P<statistics>\d+)/',
        views.test_suite_execute_record, name= "test_suite_execute_record"),
    # 执行记录相关

    re_path(r'^test_suite_statistics/(?P<suite_id>\d+)/',
            views.test_suite_statistics, name="test_suite_statistics"),
    re_path(r'^test_suite_tc_execute_record/(?P<id>\d+)/',
            views.test_suite_test_case_execute_record,
            name="test_suite_tc_execute_record"),  # 地址路径不能过长，导致读取不出id
    re_path(r'^module_test_case_statistics/(?P<module_id>\d+)/',
            views.module_test_case_statistics, name="module_test_case_statistics"),
    re_path(r'^project_test_case_statistics/(?P<project_id>\d+)/',
            views.project_test_case_statistics, name="project_test_case_statistics"),
    # 统计结果相关

    path(r'job_execute/', views.job_execute, name= "job_execute"),
    re_path(r'^change_job_status/(?P<id>([\s\S]*))/(?P<status>\d+)/',
            views.change_job_status, name= "change_job_status"),
    path(r'test_case/atp/get_job_name/',views.get_job_name, name= "get_job_name"),
    path(r'test_suite/atp/get_job_name/',views.get_job_name, name= "get_job_name"),
    # 任务相关
]

templates/sea/sea_add_test_case.html
{% extends 'atp/base.html' %}
{% load static %}
{% block title %}测试用例{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/sea/sea_add_test_case.css' %}">
{% endblock %}

{% block content %}
    <br>
    <h3 style="text-align: center">
        用例 <input type="text" id="case_name" placeholder="请输入测试用例名称" style="text-align: center" maxlength="20"> 编辑步骤
    </h3>
    <hr style="width:95%;height:1px;color:red"/>

    <iframe name="formsubmmit" style="display: none"></iframe>

    <form action="#" target="formsubmmit">
        {% csrf_token %}
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-2" style="float: right">
                        <button style="float: right;margin-right: 50px" type="button"
                                class="button1" onclick="addtmpParam();">添加
                        </button>
                    </div>
                </div>
                <div class="row" style="margin-top:10px;">
                    <div id="tblServiceList-div" style="width: 100%;">
                        <table class="table table-bordered" id="interfaceParam">
                            <thead>
                            <tr>
                                <td width="5%" style="text-align: center">步骤编号</td>
                                <td width="20%" style="text-align: center">定位路径</td>
                                <td width="17.5%" style="text-align: center">方法|操作</td>
                                <td width="15%" style="text-align: center">传入参数</td>
                                <td width="12%" style="text-align: center">步骤动作</td>
                                <td style="text-align: center">预期结果</td>
                                <td width="10%" style="text-align: center">操作</td>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-success btn-block" id="subbtn"
                style="width: 250px;height: 45px;display:block;margin:0 auto">提交
        </button>
    </form>

{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/sea/sea_add_test_case.js' %}"></script>
{% endblock %}

templates/sea/sea_test_case.html
{% extends 'atp/base.html' %}
{% load static %}
{% block title %}测试用例{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/sea/sea_test_case.css' %}">
{% endblock %}

{% block content %}
    <div id="group">
        <div id="search">
            <form action="{% url 'selenium_apps:test_case' %}" method="POST">
                {% csrf_token %}
                <input style="margin-left: 5px;" type="text" name="case_name" value="{{ case_name }}"
                       placeholder="输入用例名称">
                <input type="submit" value="搜索">
            </form>
        </div>

        <div id="load">
            <div id="addcase">
                <a href="{% url 'selenium_apps:add_test_case' %}">添加测试用例</a>
            </div>

            <div id="downloads">
                <form action="">
                    <a type="button" href="#">下载模板文件</a>
                </form>
            </div>

            <div id="uploads">
                <form action="#" method="post" enctype="multipart/form-data">
                    <div class="upload-btn-wrapper">
                        {% csrf_token %}
                        <button class="btn">选择模板文件</button>
                        <input type="file" name="file_name" accept="application/vnd.ms-excel">
                        {#只接受xls文件#}
                    </div>
                    <button id='upload-xls' class="btn" type="submit">上传模板文件</button>
                </form>
            </div>
        </div>

    </div>

    <form action="" method="POST">
        {% csrf_token %}
        <span style="margin-left: 5px;font-size: 15px">运行环境：</span>
        <select name="env">
            <option selected value="dev" style="font-size: 15px">dev</option>
            <option value="test" style="font-size: 15px">test</option>
            <option value="https" style="font-size: 15px">https</option>
        </select>
        <input type="datetime-local" style="font-size: 10px" name="ex_time">
        <input style="margin-left: 5px;font-size: 10px" type="submit" value='执行测试用例' name="ex_case" onclick="return ischecked()"/>
        <p class="glyphicon glyphicon-info-sign" title="设置执行时间，默认下一分钟后执行"></p>

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th width="5%"><input type="checkbox" id="all_select" onclick="selectOrCancelAll();"/>全选</th>
                    <th width="15%">用例名称</th>
                    <th width="15%">所属项目</th>
                    <th width="15%">所属模块</th>
                    <th width="15%">创建人员</th>
                    <th width="15%">创建时间</th>
                    <th width="15%">更新时间</th>
                    <th width="5%">操作</th>
                </tr>
                </thead>
                <tbody>

                {% for test_case in pages %}
                    <tr>
                        <td><input type="checkbox" value="{{ test_case.id }}" name="testcases_list"> {{ test_case.id }}
                        </td>
                        <td><a href="{% url 'selenium_apps:test_case_detail' test_case.id %}">{{ test_case.case_name }}</a></td>
                        <td>所属项目后期加</td>
                        <td>所属项目后期加</td>
                        <td>{{ test_case.user }}</td>
                        <td>{{ test_case.create_time }}</td>
                        <td>更新时间后期加</td>
                        <td>
                            <a href="{% url 'selenium_apps:update_test_case' test_case.id %}">修改</a>
                            <a href="{% url 'selenium_apps:delete_test_case' test_case.id %}">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </form>

    <div id="pages" class="text-center">
        <nav>
            <ul class="pagination">
                <li class="step-links">
                    {% if pages.has_previous %}
                        <a class='active' href="?page={{ pages.previous_page_number }}">上一页</a>
                    {% endif %}

                    <span class="current">
                        第 {{ pages.number }} 页 / 共 {{ pages.paginator.num_pages }} 页</span>

                    {% if pages.has_next %}
                        <a class='active' href="?page={{ pages.next_page_number }}">下一页</a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>

{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/sea/sea_test_case.js' %}"></script>
{% endblock %}

templates/sea/sea_test_case_detail.html
{% extends 'atp/base.html' %}
{% load static %}
{% block title %}用例详情{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/sea/sea_add_test_case.css' %}">
    {#可以复用#}
{% endblock %}

{% block content %}
    <br>
    <h3 style="text-align: center">
        用例【{{ test_case.case_name }}】详情
    </h3>
    <span id="case_id" style="display: none">{{ test_case.id }}</span>
    <hr style="width:95%;height:1px;color:red"/>

    <iframe name="formsubmmit" style="display: none"></iframe>

    <form action="#" target="formsubmmit">
        {% csrf_token %}
        <div class="card">
            <div class="card-body">
                <div class="row" style="margin-top:10px;">
                    <div id="tblServiceList-div" style="width: 100%;">
                        <table class="table table-bordered" id="interfaceParam">
                            <thead>
                            <tr>
                                <td width="5%" style="text-align: center">步骤编号</td>
                                <td width="25%" style="text-align: center">定位路径</td>
                                <td width="17.5%" style="text-align: center">方法|操作</td>
                                <td width="20%" style="text-align: center">传入参数</td>
                                <td width="12%" style="text-align: center">步骤动作</td>
                                <td style="text-align: center">预期结果</td>
                            </tr>
                            </thead>
                            {% for step in test_case_steps %}
                                <tr>
                                    <td style="text-align: center">{{ step.0 }}</td>
                                    <td>
                                        <input id=LocationPath{{ step.0 }} style='width: 100%;' type='text'
                                               value="{{ step.1 }}">
                                    </td>
                                    <td>
                                        <input id=Method{{ step.0 }} style='width: 100%;' type='text'
                                               value="{{ step.2 }}">
                                    </td>
                                    <td>
                                        <input id=Parameter{{ step.0 }} style='width: 100%;' type='text'
                                               value="{{ step.3 }}">
                                    </td>
                                    <td>
                                        <input id=Action{{ step.0 }} style='width: 100%;' type='text'
                                               value="{{ step.4 }}">
                                    </td>
                                    <td>
                                        <input id=Expected{{ step.0 }} style='width: 100%;' type='text'
                                               value="{{ step.5 }}">
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </form>

{% endblock %}

templates/sea/sea_update_test_case.html
{% extends 'atp/base.html' %}
{% load static %}
{% block title %}修改用例{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/sea/sea_add_test_case.css' %}">
    {#可以复用#}
{% endblock %}

{% block content %}
    <br>
    <h3 style="text-align: center">
        用例【{{ test_case.case_name }}】编辑步骤
    </h3>
    <span id="case_id" style="display: none">{{ test_case.id }}</span>
    <hr style="width:95%;height:1px;color:red"/>

    <iframe name="formsubmmit" style="display: none"></iframe>

    <form action="#" target="formsubmmit">
        {% csrf_token %}
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-2" style="float: right">
                        <button style="float: right;margin-right: 50px" type="button"
                                class="button1" onclick="addtmpParam();">添加
                        </button>
                    </div>
                </div>
                <div class="row" style="margin-top:10px;">
                    <div id="tblServiceList-div" style="width: 100%;">
                        <table class="table table-bordered" id="interfaceParam">
                            <thead>
                            <tr>
                                <td width="5%" style="text-align: center">步骤编号</td>
                                <td width="20%" style="text-align: center">定位路径</td>
                                <td width="17.5%" style="text-align: center">方法|操作</td>
                                <td width="15%" style="text-align: center">传入参数</td>
                                <td width="12%" style="text-align: center">步骤动作</td>
                                <td style="text-align: center">预期结果</td>
                                <td width="10%" style="text-align: center">操作</td>
                            </tr>
                            </thead>
                            {% for step in test_case_steps %}
                                <tr>
                                    <td style="text-align: center">{{ step.0 }}</td>
                                    <td>
                                        <input id=LocationPath{{ step.0 }} style='width: 100%;' type='text'
                                               value="{{ step.1 }}">
                                    </td>
                                    <td>
                                        <input id=Method{{ step.0 }} style='width: 100%;' type='text'
                                               value="{{ step.2 }}">
                                    </td>
                                    <td>
                                        <input id=Parameter{{ step.0 }} style='width: 100%;' type='text'
                                               value="{{ step.3 }}">
                                    </td>
                                    <td>
                                        <input id=Action{{ step.0 }} style='width: 100%;' type='text'
                                               value="{{ step.4 }}">
                                    </td>
                                    <td>
                                        <input id=Expected{{ step.0 }} style='width: 100%;' type='text'
                                               value="{{ step.5 }}">
                                    </td>
                                    <td>
                                        <div id=operate{{ step.0 }} style="text-align: center">
                                            <a style="cursor:pointer;color:red;"
                                               onclick="deleteInterfaceParam();">删除</a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-success btn-block" id="subbtn"
                style="width: 250px;height: 45px;display:block;margin:0 auto">修改
        </button>
    </form>

{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/sea/sea_update_test_case.js' %}"></script>
{% endblock %}